#!/usr/bin/env python3
"""
REEcord Launcher — Single entry point.

Usage:
  python launcher.py

What it does:
  1. Checks dependencies (Docker, Ollama, Python packages)
  2. If .env is not configured → opens setup.html in browser
  3. If .env is ready → starts proxy, opens chat.html in browser
"""

import os
import sys
import json
import time
import threading
import subprocess
import webbrowser
import urllib.request
import urllib.error
from pathlib import Path

# ── Package check ─────────────────────────────────────────────────────────────
def _ensure_packages():
    needed = []
    try: import flask
    except ImportError: needed.append("flask")
    try: import requests
    except ImportError: needed.append("requests")

    if needed:
        print(f"[Launcher] Installing missing packages: {', '.join(needed)}")
        subprocess.check_call([sys.executable, "-m", "pip", "install", *needed, "-q"])

_ensure_packages()

from flask import Flask, request, redirect, send_from_directory, jsonify

# ── Paths ─────────────────────────────────────────────────────────────────────
PROJECT_DIR   = Path(__file__).resolve().parent
WEB_UI_DIR    = PROJECT_DIR / "web_ui"
ENV_FILE      = PROJECT_DIR / ".env"
LAUNCHER_PORT = 5000

app = Flask(__name__)

# ── .env ──────────────────────────────────────────────────────────────────────
def load_env() -> dict:
    if not ENV_FILE.exists():
        return {}
    result = {}
    with open(ENV_FILE, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, val = line.partition("=")
            result[key.strip()] = val.strip()
    return result


def save_env(data: dict):
    existing = load_env()
    existing.update(data)
    lines = [
        "# REEcord Configuration — auto-generated by launcher.py",
        f"GENSYN_PRIVATE_KEY={existing.get('GENSYN_PRIVATE_KEY', '')}",
        f"GENSYN_WALLET_ADDRESS={existing.get('GENSYN_WALLET_ADDRESS', '')}",
        f"PINATA_API_KEY={existing.get('PINATA_API_KEY', '')}",
        "GENSYN_RPC_URL=https://gensyn-testnet.g.alchemy.com/public",
        "REE_MODEL=Qwen/Qwen2-0.5B",
        "REE_MAX_TOKENS=50",
    ]
    with open(ENV_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def is_configured() -> bool:
    env = load_env()
    pk = env.get("GENSYN_PRIVATE_KEY", "")
    return bool(pk and pk != "0x" and len(pk) > 10)

# ── System checks ─────────────────────────────────────────────────────────────
def check_docker() -> bool:
    try:
        r = subprocess.run(
            ["docker", "info"], capture_output=True, timeout=6
        )
        return r.returncode == 0
    except Exception:
        return False


def check_ollama() -> dict:
    """Detect which port Ollama is running on."""
    for port in [11436, 11434]:
        try:
            url = f"http://localhost:{port}/api/tags"
            with urllib.request.urlopen(url, timeout=3) as r:
                data = json.loads(r.read())
                models = [m["name"] for m in data.get("models", [])]
                return {"running": True, "port": port, "models": models}
        except Exception:
            continue
    return {"running": False, "port": None, "models": []}


def check_packages() -> bool:
    try:
        import web3
        from Crypto.Cipher import AES
        return True
    except ImportError:
        return False

# ── Proxy management ──────────────────────────────────────────────────────────
_proxy_proc = None
_proxy_lock = threading.Lock()


def start_proxy(ollama_port: int = 11436):
    global _proxy_proc
    with _proxy_lock:
        if _proxy_proc and _proxy_proc.poll() is None:
            return   # Already running

        env = load_env()
        environ = os.environ.copy()
        environ.update(env)
        environ["REE_OLLAMA_URL"] = f"http://localhost:{ollama_port}"
        environ["REE_PROXY_PORT"] = "11435"

        python_exe   = sys.executable
        proxy_script = str(PROJECT_DIR / "ollama_proxy.py")

        print(f"[Launcher] Starting proxy: {python_exe} {proxy_script}")
        print(f"[Launcher] Ollama port: {ollama_port}")

        _proxy_proc = subprocess.Popen(
            [python_exe, proxy_script],
            env=environ,
            cwd=str(PROJECT_DIR),
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        )
        print(f"[Launcher] Proxy PID: {_proxy_proc.pid}")

        # Pipe proxy output to terminal
        def _pipe():
            for line in iter(_proxy_proc.stdout.readline, ""):
                print(f"  [proxy] {line}", end="", flush=True)
        threading.Thread(target=_pipe, daemon=True).start()

        # Wait for proxy to come up (max 8s)
        for _ in range(16):
            time.sleep(0.5)
            try:
                urllib.request.urlopen("http://localhost:11435/reerecord/status", timeout=1)
                print("[Launcher] Proxy ready ✓")
                return
            except Exception:
                pass
        print("[Launcher] Proxy is slow to start, continuing in background.")


def proxy_running() -> bool:
    if _proxy_proc is None or _proxy_proc.poll() is not None:
        return False
    try:
        urllib.request.urlopen("http://localhost:11435/reerecord/status", timeout=1)
        return True
    except Exception:
        return False

# ── Flask routes ──────────────────────────────────────────────────────────────
@app.route("/")
def root():
    if is_configured():
        return redirect("/chat")
    return redirect("/setup")


@app.route("/setup")
def setup_page():
    return send_from_directory(str(WEB_UI_DIR), "setup.html")


@app.route("/chat")
def chat_page():
    if not is_configured():
        return redirect("/setup")
    return send_from_directory(str(WEB_UI_DIR), "chat.html")


@app.route("/<path:filename>")
def static_files(filename):
    return send_from_directory(str(WEB_UI_DIR), filename)


@app.route("/api/status")
def api_status():
    ollama = check_ollama()
    return jsonify({
        "configured":    is_configured(),
        "docker":        check_docker(),
        "ollama":        ollama["running"],
        "ollama_port":   ollama["port"],
        "ollama_models": ollama["models"],
        "packages":      check_packages(),
        "proxy":         proxy_running(),
    })


@app.route("/api/save-config", methods=["POST"])
def api_save_config():
    data = request.get_json(force=True) or {}
    pk   = data.get("private_key", "").strip()
    addr = data.get("wallet_address", "").strip()
    jwt  = data.get("pinata_jwt", "").strip()

    if not pk:
        return jsonify({"error": "Private key is required"}), 400

    # Add 0x prefix if missing
    if not pk.startswith("0x") and len(pk) == 64:
        pk = "0x" + pk

    save_env({
        "GENSYN_PRIVATE_KEY":    pk,
        "GENSYN_WALLET_ADDRESS": addr,
        "PINATA_API_KEY":        jwt,
    })

    # Detect Ollama port and start proxy
    ollama = check_ollama()
    port   = ollama.get("port", 11436) or 11436
    threading.Thread(target=start_proxy, args=(port,), daemon=True).start()

    return jsonify({"ok": True, "redirect": "/chat"})


@app.route("/api/start-proxy", methods=["POST"])
def api_start_proxy():
    ollama = check_ollama()
    port   = ollama.get("port", 11436) or 11436
    threading.Thread(target=start_proxy, args=(port,), daemon=True).start()
    return jsonify({"ok": True})


@app.route("/api/reset-config", methods=["POST"])
def api_reset_config():
    """Reset configuration (go back to setup)."""
    global _proxy_proc
    if _proxy_proc and _proxy_proc.poll() is None:
        _proxy_proc.terminate()
    save_env({
        "GENSYN_PRIVATE_KEY":    "0x",
        "GENSYN_WALLET_ADDRESS": "",
        "PINATA_API_KEY":        "",
    })
    return jsonify({"ok": True, "redirect": "/setup"})

# ── Main ──────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print()
    print("╔══════════════════════════════════════════════════════════╗")
    print("║              REEcord Launcher  v2.0                     ║")
    print("╚══════════════════════════════════════════════════════════╝")
    print()

    docker = check_docker()
    ollama = check_ollama()
    pkgs   = check_packages()

    print(f"  Docker   : {'✓ running' if docker else '✗ not running'}")
    print(f"  Ollama   : {'✓ port ' + str(ollama['port']) if ollama['running'] else '✗ not running'}")
    print(f"  Packages : {'✓ installed' if pkgs else '✗ missing (will install automatically)'}")
    print(f"  Config   : {'✓ ready' if is_configured() else '✗ setup required'}")
    print()

    if not docker:
        print("  ⚠  Docker Desktop is not running.")
        print("     Docker is required for REE. Please start Docker Desktop.")
        print()

    if not ollama["running"]:
        print("  ⚠  Ollama is not running.")
        print("     Start Ollama and pull at least one model.")
        print()

    # If configured, start proxy immediately
    if is_configured():
        port = ollama.get("port", 11436) or 11436
        threading.Thread(target=start_proxy, args=(port,), daemon=True).start()
        time.sleep(0.8)
        target_url = f"http://localhost:{LAUNCHER_PORT}/chat"
        print(f"  → Opening chat: {target_url}")
    else:
        target_url = f"http://localhost:{LAUNCHER_PORT}/setup"
        print(f"  → Opening setup: {target_url}")

    print()
    print(f"  Press Ctrl+C to stop.")
    print()

    def _open():
        time.sleep(1.5)
        webbrowser.open(target_url)
    threading.Thread(target=_open, daemon=True).start()

    try:
        app.run(host="0.0.0.0", port=LAUNCHER_PORT, debug=False, use_reloader=False)
    except KeyboardInterrupt:
        print("\n[Launcher] Shutting down…")

        # Graceful shutdown: wait for active finalize jobs
        try:
            import urllib.request as _ur
            import json as _json
            resp = _ur.urlopen("http://localhost:11435/reerecord/status", timeout=2)
            active = _json.loads(resp.read()).get("active_jobs", 0)
            if active > 0:
                print(f"[Launcher] Waiting for {active} active finalize job(s) to complete…")
                print("[Launcher] Press Ctrl+C again to force quit.")
                for i in range(60):
                    time.sleep(5)
                    try:
                        resp2 = _ur.urlopen("http://localhost:11435/reerecord/status", timeout=2)
                        active2 = _json.loads(resp2.read()).get("active_jobs", 0)
                        if active2 == 0:
                            print("[Launcher] All jobs complete.")
                            break
                        print(f"[Launcher] Still waiting… ({active2} job(s) running, {(i+1)*5}s elapsed)")
                    except Exception:
                        break
        except Exception:
            pass

        if _proxy_proc and _proxy_proc.poll() is None:
            _proxy_proc.terminate()
